"""Supported UI-independent application API for the recovered invariant program."""

from .branch_catalog import (
    DEFAULT_EVALUATION_MODEL_IDS,
    EvaluationBranchDescriptor,
    branch_ids_for_models,
    get_evaluation_branch,
    get_evaluation_model,
    list_evaluation_branches,
)
from .catalog_examples import ApplicationCatalogExample, get_catalog_example, list_catalog_examples
from .custom_rmatrix import (
    ApplicationCustomBraidOperatorResult,
    ApplicationCustomMatrixValidation,
    ApplicationCustomRMatrixModel,
    build_custom_rmatrix_model,
    evaluate_custom_braid_operator,
    parse_custom_matrix,
    serialize_custom_braid_operator_result,
    validate_custom_matrix,
)

from .braid_evaluation import (
    BraidInputState,
    build_catalog_braid_input,
    build_custom_braid_input,
    build_custom_braid_word,
    evaluate_braid_input,
    evaluate_braid_input_result,
    evaluate_braid_word,
    evaluate_braid_result,
    evaluate_catalog_example,
    evaluate_catalog_result,
    evaluate_custom_braid,
    evaluate_custom_result,
    parse_generator_text,
)
from .results import (
    ApplicationBraidResult,
    ApplicationBranchResult,
    application_braid_result_from_internal,
    application_branch_result_from_internal,
    filter_application_braid_result,
    format_application_braid_result,
    format_application_branch_result,
    serialize_application_braid_result,
)
from .errors import (
    ApplicationServiceError,
    BraidInputError,
    BraidInputValidationError,
    GeneratorParseError,
    UnknownCatalogExampleError,
    UnknownEvaluationBranchError,
    UnknownEvaluationModelError,
    CustomBraidOperatorError,
    CustomMatrixInputError,
)

__all__ = [
    "ApplicationServiceError",
    "ApplicationBraidResult",
    "ApplicationBranchResult",
    "ApplicationCatalogExample",
    "ApplicationCustomBraidOperatorResult",
    "ApplicationCustomMatrixValidation",
    "ApplicationCustomRMatrixModel",
    "BraidInputError",
    "BraidInputState",
    "BraidInputValidationError",
    "DEFAULT_EVALUATION_MODEL_IDS",
    "EvaluationBranchDescriptor",
    "GeneratorParseError",
    "CustomBraidOperatorError",
    "CustomMatrixInputError",
    "UnknownCatalogExampleError",
    "UnknownEvaluationBranchError",
    "UnknownEvaluationModelError",
    "branch_ids_for_models",
    "application_braid_result_from_internal",
    "application_branch_result_from_internal",
    "build_catalog_braid_input",
    "build_custom_braid_input",
    "build_custom_braid_word",
    "build_custom_rmatrix_model",
    "evaluate_braid_input",
    "evaluate_braid_input_result",
    "evaluate_braid_word",
    "evaluate_braid_result",
    "evaluate_catalog_example",
    "evaluate_catalog_result",
    "evaluate_custom_braid",
    "evaluate_custom_result",
    "evaluate_custom_braid_operator",
    "filter_application_braid_result",
    "format_application_braid_result",
    "format_application_branch_result",
    "get_evaluation_branch",
    "get_evaluation_model",
    "get_catalog_example",
    "list_catalog_examples",
    "list_evaluation_branches",
    "parse_generator_text",
    "parse_custom_matrix",
    "serialize_custom_braid_operator_result",
    "serialize_application_braid_result",
    "validate_custom_matrix",
]
