"""Invariant-result objects and raw trace computations for braid closures."""

from .eyb_invariant import (
    EYBData,
    build_sl2_fundamental_eyb_data,
    build_sl3_fundamental_eyb_data,
    compute_eyb_invariant,
)
from .benchmark import BenchmarkEntry, evaluate_braid_example, evaluate_catalog
from .branch_registry import (
    evaluate_all_current_branches,
    evaluate_sl2_fundamental_branch,
    evaluate_sl2_spin1_branch,
    evaluate_sl3_fundamental_branch,
)
from .branch_formatter import (
    format_branch_result,
    format_catalog_benchmark,
    format_multibranch_entry,
)
from .branch_results import InvariantBranchResult
from .convention_audit import (
    BraidSideConventionData,
    ConventionComparisonResult,
    RawSideConventionData,
    build_braid_side_convention_data,
    build_raw_side_convention_data,
    compare_raw_and_braid_side_conventions,
)
from .compare_9x9_benchmark import (
    DEFAULT_9X9_COMPARISON_PAIRS,
    NINE_BY_NINE_COMPARISON_CONCLUSION,
    SL2_3D_CHANNEL_EXPLANATION,
    SL3_FUNDAMENTAL_9X9_CHANNEL_EXPLANATION,
    NineByNineComparisonPair,
    NineByNineComparisonSummary,
    NineByNinePairComparisonResult,
    classify_9x9_pair,
    evaluate_9x9_pair,
    evaluate_9x9_pairs,
    evaluate_default_9x9_discriminating_power,
)
from .eyb_diagnostics import (
    PartialTraceDiagnostic,
    StabilizationDiagnostic,
    diagnose_partial_trace,
    diagnose_stabilization,
    make_local_object_variant,
    partial_trace_second,
    scalar_multiple_if_any,
)
from .jones_debug import (
    JonesComparisonResult,
    SupportSignature,
    TransformationCandidate,
    compare_current_p2_with_jones,
    compare_named_current_p2_with_jones,
    convert_target_to_q,
    make_reference_case_from_example,
    search_monomial_match,
    support_signature,
)
from .jones_invariant import (
    DEFAULT_JONES_VARIABLE_CONVENTION,
    JonesInvariantResult,
    compute_sl2_jones_compatible_output,
    compute_sl2_reduced_p2,
    current_sl2_unknot_normalization,
)
from .sl2_3d_candidate_benchmark import (
    Sl2ThreeDimCandidateBenchmarkEntry,
    evaluate_default_sl2_3d_candidate_benchmark,
    evaluate_sl2_3d_candidate_example,
    evaluate_sl2_3d_candidate_examples,
)
from .sl2_3d_colored_jones_candidate import (
    SL2_3D_BRANCH_STATUS,
    SL2_3D_CANDIDATE_OUTPUT_LABEL,
    SL2_3D_USER_FACING_NAME,
    SL2_3D_VARIABLE_CONVENTION,
    Sl2ThreeDimCandidateResult,
    compute_sl2_3d_candidate_output,
    compute_sl2_3d_candidate_unreduced_output,
    current_sl2_3d_candidate_alpha,
    current_sl2_3d_candidate_beta,
    current_sl2_3d_candidate_mu,
    current_sl2_3d_unknot_normalization,
)
from .jones_reference_cases import (
    JonesReferenceCase,
    get_default_jones_reference_cases,
    get_jones_reference_case,
)
from .legacy_branch_registry import (
    LEGACY_SL2_3D_USER_FACING_NAME,
    evaluate_all_legacy_branches,
    evaluate_sl2_3d_legacy_raw_branch,
)
from .legacy_multibranch_benchmark import (
    LegacyMultiBranchBenchmarkEntry,
    evaluate_legacy_catalog_across_branches,
    evaluate_legacy_example_across_branches,
)
from .markov_checks import (
    ConjugationCheckResult,
    ExpressionComparison,
    MarkovCheckBundle,
    StabilizationCheckResult,
    check_conjugation_invariance,
    check_stabilization_invariance,
    conjugate_braid_word,
    default_conjugator_generators,
    stabilize_braid_word,
)
from .multibranch_benchmark import (
    MultiBranchBenchmarkEntry,
    evaluate_catalog_across_branches,
    evaluate_example_across_branches,
)
from .polynomial_result import InvariantResult
from .quantum_trace import BraidClosureData, compute_raw_closure_trace, make_braid_closure_data

__all__ = [
    "BenchmarkEntry",
    "InvariantBranchResult",
    "format_branch_result",
    "format_catalog_benchmark",
    "format_multibranch_entry",
    "BraidSideConventionData",
    "ConjugationCheckResult",
    "ConventionComparisonResult",
    "DEFAULT_9X9_COMPARISON_PAIRS",
    "DEFAULT_JONES_VARIABLE_CONVENTION",
    "EYBData",
    "ExpressionComparison",
    "InvariantResult",
    "JonesComparisonResult",
    "JonesInvariantResult",
    "JonesReferenceCase",
    "LegacyMultiBranchBenchmarkEntry",
    "MarkovCheckBundle",
    "MultiBranchBenchmarkEntry",
    "NineByNineComparisonPair",
    "NineByNineComparisonSummary",
    "NineByNinePairComparisonResult",
    "PartialTraceDiagnostic",
    "RawSideConventionData",
    "BraidClosureData",
    "SupportSignature",
    "StabilizationDiagnostic",
    "StabilizationCheckResult",
    "TransformationCandidate",
    "build_braid_side_convention_data",
    "build_raw_side_convention_data",
    "build_sl2_fundamental_eyb_data",
    "build_sl3_fundamental_eyb_data",
    "check_conjugation_invariance",
    "check_stabilization_invariance",
    "evaluate_all_current_branches",
    "evaluate_all_legacy_branches",
    "compare_current_p2_with_jones",
    "compare_named_current_p2_with_jones",
    "classify_9x9_pair",
    "compare_raw_and_braid_side_conventions",
    "conjugate_braid_word",
    "compute_eyb_invariant",
    "convert_target_to_q",
    "compute_sl2_jones_compatible_output",
    "compute_sl2_reduced_p2",
    "diagnose_partial_trace",
    "diagnose_stabilization",
    "current_sl2_unknot_normalization",
    "current_sl2_3d_candidate_alpha",
    "current_sl2_3d_candidate_beta",
    "current_sl2_3d_candidate_mu",
    "current_sl2_3d_unknot_normalization",
    "make_braid_closure_data",
    "make_local_object_variant",
    "make_reference_case_from_example",
    "compute_raw_closure_trace",
    "compute_sl2_3d_candidate_output",
    "compute_sl2_3d_candidate_unreduced_output",
    "default_conjugator_generators",
    "evaluate_braid_example",
    "evaluate_catalog_across_branches",
    "evaluate_catalog",
    "evaluate_default_9x9_discriminating_power",
    "evaluate_example_across_branches",
    "evaluate_9x9_pair",
    "evaluate_9x9_pairs",
    "evaluate_default_sl2_3d_candidate_benchmark",
    "evaluate_legacy_catalog_across_branches",
    "evaluate_legacy_example_across_branches",
    "evaluate_sl2_3d_candidate_example",
    "evaluate_sl2_3d_candidate_examples",
    "evaluate_sl2_3d_legacy_raw_branch",
    "evaluate_sl2_fundamental_branch",
    "evaluate_sl2_spin1_branch",
    "evaluate_sl3_fundamental_branch",
    "get_default_jones_reference_cases",
    "get_jones_reference_case",
    "SL2_3D_BRANCH_STATUS",
    "SL2_3D_CANDIDATE_OUTPUT_LABEL",
    "SL2_3D_CHANNEL_EXPLANATION",
    "SL2_3D_USER_FACING_NAME",
    "SL2_3D_VARIABLE_CONVENTION",
    "SL3_FUNDAMENTAL_9X9_CHANNEL_EXPLANATION",
    "NINE_BY_NINE_COMPARISON_CONCLUSION",
    "LEGACY_SL2_3D_USER_FACING_NAME",
    "Sl2ThreeDimCandidateBenchmarkEntry",
    "Sl2ThreeDimCandidateResult",
    "partial_trace_second",
    "scalar_multiple_if_any",
    "search_monomial_match",
    "stabilize_braid_word",
    "support_signature",
]

